import { Property, Lead, ScheduledPost, Agent } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Luxury Villa',
    location_city: 'Camps Bay',
    location_area: 'Cape Town',
    price: 18500000,
    status: 'active',
    image: 'https://picsum.photos/seed/capetown1/800/600',
    agent: 'Sipho Dlamini',
    type: 'Villa',
    beds: 5,
    baths: 4,
    sqft: 420,
  },
  {
    id: '2',
    title: 'Penthouse with City Views',
    location_city: 'Sandton',
    location_area: 'Johannesburg',
    price: 9800000,
    status: 'pending',
    image: 'https://picsum.photos/seed/jhb1/800/600',
    agent: 'Lerato Khumalo',
    type: 'Apartment',
    beds: 3,
    baths: 2,
    sqft: 210,
  },
  {
    id: '3',
    title: 'Beachfront Bungalow',
    location_city: 'Umhlanga',
    location_area: 'Durban',
    price: 6200000,
    status: 'active',
    image: 'https://picsum.photos/seed/durban1/800/600',
    agent: 'Sipho Dlamini',
    type: 'Bungalow',
    beds: 4,
    baths: 3,
    sqft: 310,
  },
  {
    id: '4',
    title: 'Cluster Home in Secure Estate',
    location_city: 'Centurion',
    location_area: 'Pretoria',
    price: 3450000,
    status: 'active',
    image: 'https://picsum.photos/seed/pretoria1/800/600',
    agent: 'Lerato Khumalo',
    type: 'Cluster',
    beds: 3,
    baths: 2,
    sqft: 195,
  },
];

export const agents: Agent[] = [
  {
    id: '1',
    full_name: 'Sipho Dlamini',
    email: 'sipho@proppost.co.za',
    cellphone_number: '+27 82 123 4567',
    profile_photo_url: 'https://i.pravatar.cc/150?u=sipho',
    role_optional: 'Senior Agent',
    agency_id: 'agency-1',
  },
  {
    id: '2',
    full_name: 'Lerato Khumalo',
    email: 'lerato@proppost.co.za',
    cellphone_number: '+27 83 987 6543',
    profile_photo_url: 'https://i.pravatar.cc/150?u=lerato',
    role_optional: 'Listing Specialist',
    agency_id: 'agency-1',
  },
  {
    id: '3',
    full_name: 'Ashwin Naidoo',
    email: 'ashwin@proppost.co.za',
    cellphone_number: '+27 71 555 0198',
    profile_photo_url: 'https://i.pravatar.cc/150?u=ashwin',
    role_optional: 'Commercial Agent',
    agency_id: 'agency-1',
  },
];

export const leads: Lead[] = [
  {
    id: '1',
    contactName: 'Thabo Mokoena',
    contactEmail: 'thabo@gmail.com',
    contactPhone: '+27 84 111 2222',
    status: 'New',
    propertyId: '1',
    propertyTitle: 'Modern Luxury Villa',
    agentId: '1',
    agentName: 'Sipho Dlamini',
    source: 'Facebook',
    createdAt: '2026-04-19T10:00:00Z',
    updatedAt: '2026-04-19T10:00:00Z',
  },
  {
    id: '2',
    contactName: 'Priya Naidoo',
    contactEmail: 'priya.n@outlook.com',
    contactPhone: '+27 79 333 4444',
    status: 'Contacted',
    propertyId: '2',
    propertyTitle: 'Penthouse with City Views',
    agentId: '2',
    agentName: 'Lerato Khumalo',
    source: 'Instagram',
    createdAt: '2026-04-18T14:30:00Z',
    updatedAt: '2026-04-18T14:30:00Z',
  },
  {
    id: '3',
    contactName: 'Gareth van der Merwe',
    contactEmail: 'gareth@vdm.co.za',
    contactPhone: '+27 82 555 6666',
    status: 'Qualified',
    propertyId: '1',
    propertyTitle: 'Modern Luxury Villa',
    agentId: '1',
    agentName: 'Sipho Dlamini',
    source: 'LinkedIn',
    createdAt: '2026-04-17T09:15:00Z',
    updatedAt: '2026-04-17T09:15:00Z',
  },
  {
    id: '4',
    contactName: 'Nomsa Zulu',
    contactEmail: 'nomsa.zulu@webmail.co.za',
    contactPhone: '+27 61 777 8888',
    status: 'New',
    propertyId: '3',
    propertyTitle: 'Beachfront Bungalow',
    agentId: '3',
    agentName: 'Ashwin Naidoo',
    source: 'Property24',
    createdAt: '2026-04-16T11:00:00Z',
    updatedAt: '2026-04-16T11:00:00Z',
  },
];

export const scheduledPosts: ScheduledPost[] = [
  {
    id: '1',
    propertyId: '1',
    platform: 'instagram',
    type: 'post',
    caption: 'Stunning luxury villa in Camps Bay — ocean views, 5 beds, and a pool that dreams are made of. DM us or WhatsApp to book a viewing. #CapeTown #LuxuryProperty #PropPost #CampsBay',
    scheduledAt: '2026-04-28T10:00:00Z',
    status: 'scheduled',
    image: 'https://picsum.photos/seed/capetown1/800/600',
  },
  {
    id: '2',
    propertyId: '2',
    platform: 'facebook',
    type: 'post',
    caption: 'New to market! Penthouse living in the heart of Sandton. 3 bedrooms, panoramic city views, 24hr security. R 9.8M. Contact Lerato today. #Sandton #Johannesburg #ForSale',
    scheduledAt: '2026-04-29T08:00:00Z',
    status: 'scheduled',
    image: 'https://picsum.photos/seed/jhb1/800/600',
  },
];